### ISSUE TITLE
Eye lid no longer blink. (Version 12)

### ISSUE THREAD

**Issue by MioBlackHeart** [ButzYung/SystemAnimatorOnline#21] opened 2023-07-27 12:15 UTC
As title say. 

Version 12 does not track eye blinking no more while Version 11 works fine. While it does look like you are blinking in XR. It doesn't translate into Vnyan or VSeeFace (or any of the like)

![2023-07-27 05_14_38-](https://github.com/ButzYung/SystemAnimatorOnline/assets/138373550/a1a3684c-fa2e-4d85-aee4-2993c0e3a6fd)
![2023-07-27 05_14_30-Window](https://github.com/ButzYung/SystemAnimatorOnline/assets/138373550/e9d51483-1da8-40b8-90b5-00044af084bf)
![2023-07-27 05_14_24-](https://github.com/ButzYung/SystemAnimatorOnline/assets/138373550/76cdaa31-ad07-4f62-9c95-4a62e7b8463f)

**Comment by MioBlackHeart** [comment] 2023-07-27 12:16
![2023-07-27 05_14_17-](https://github.com/ButzYung/SystemAnimatorOnline/assets/138373550/b120ee42-3983-4e15-ba61-2527ba1d72ed)

**Comment by ButzYung** [comment] 2023-07-27 12:52
@MioBlackHeart Bug confirmed. Will fix it and release a hotfix ASAP

**Comment by MioBlackHeart** [comment] 2023-07-27 13:17
> 

Glad you on it fast. But no rush friend. :) Thanks for making this awesome tracker. Supported yah on your Kofi. Keep up the good work!

**Comment by ButzYung** [comment] 2023-07-27 16:26
@MioBlackHeart Fixed in v0.12.0b. Check it out and let me know if there is any other issue.

**Comment by ButzYung** [comment] 2023-07-28 07:46
@MioBlackHeart Yeah I am aware of the speech bubble issues. Will fix it in next update.

**Comment by MioBlackHeart** [comment] 2023-07-30 00:25
> @MioBlackHeart Yeah I am aware of the speech bubble issues. Will fix it in next update.

Another request if possible. 
For Streamer Mode: Can it also hide the UI if that can be option in streamer mode? "Overlay & UI > User Interface >Off"

**Comment by ButzYung** [comment] 2023-07-30 16:27
> Another request if possible. For Streamer Mode: Can it also hide the UI if that can be option in streamer mode? "Overlay & UI > User Interface >Off"

By default, Streamer Mode already provides an option to turn off UI at the end. However, if you use VMC protocol, the ending option will be hiding 3D avatar instead of turning off UI, which is intentional as I think turning off UI is no longer a necessity since you probably won't be streaming on XR Animator's window while using other VMC apps.

**Comment by MioBlackHeart** [comment] 2023-07-30 20:23
well in my case, i been having to hide the UI as it gets in the way for me. but that's just me and reason why i wanted to ask for it to be included in the streamer mode. but its not a big deal.

**Closed** 2023-08-04 22:38 UTC
